### ISSUE TITLE
Think Aloud Testing outcomes document

### ISSUE THREAD

**Issue by seamustuohy** [OpenInternet/co-pilot#33]
Using the [list of user-interface elements](https://github.com/OpenInternet/co-pilot/wiki/User-Interface-Elements) as a guide create a document describing the outputs of the user think aloud testing.

**Comment by megdeb** [comment]
A chart of each wire frame data was made in order to compare "think aloud testing" findings side-by-side and identify points where similar views were shared. 

There were 12 original wire frames created and the initial think aloud testing was done with 5 digital security trainers.

**Comment by megdeb** [comment]
@elationfoundation do you think I should upload the photos I took of each chart (one per wire frame)?

**Comment by megdeb** [comment]
## General Takeaways

- any time there is a change to a password, access point name, rule, or profile - there must be a confirmation that the changes have been saved
- set-up trainer password, access point name and password first; then tutorial on how to create a rule and profile
- ensure both arrows and numbers in the tutorial can navigate the user back-and-forth
-

**Comment by megdeb** [comment]
no where near closed. my bad

**Comment by megdeb** [comment]
### General Takeaways
- any time there is a change to a password, access point name, rule, or profile - there must be a confirmation that the changes have been saved
- disclaimers should be added (specifically regarding any traces of Co-Pilot that may be left behind for both the trainer and trainee)
- set-up trainer password, access point name and password first; then tutorial on how to create a rule and profile
- ensure both arrows and numbers in the tutorial can navigate the user back-and-forth

**Comment by megdeb** [comment]
### Welcome

• TXT: Change verbiage to take out Co-Pilot twice
• ADD: Make sure both arrow and numbers navigate through

### Setup Trainer Password

• TXT: Change “trainer password” to “admin” password? This might help ease some of the confusion
• ADD: save button or confirmation bubble when you click next that password has been saved

### Access Point Name and Password Setup

• TXT: add “via access point and password below”
o   Will help with confusion
• ADD: save button or confirmation bubble when you click next that password has been saved
• ADD: text bubble explaining each
o   Access Point 
 Mention this can be reset at a later time
o   Access Point Password
 Mention this can be reset at a later time

### Create First Rule

• TXT: change ”sub-target” OR explain somewhere
• ADD: text bubble or hyperlinks explaining URL, HTTP, HTTPS, DNS
• ADD: a way to see an example first

### Create Profile

• ADD: at least one example of a combination rule

### Reset (takeaways still important event though there is no longer a reset page)

• Unclear the entire first 6 slides were a tutorial
• Assumption is that rules will be saved on reset

### Login

• ADD: label “trainer username”
• ADD: label “trainer password”
• ADD: “forgot password” link or something explaining what to do in this case

### Menu

• All thought rules were saved previously
• ADD: text bubbles that explain what each does as you hover over 
o   New Profile
o   Load Profile
o   Admin Config

### New Profile

• ADD: labels
• FUNCTION: Be able to try rules out (with the ‘on’ button) before saving
• FUNCTION: possibly pre-populate  some DNS blocking options since it is trickier

### Save Profile

• FUNCTION: be able to save profile to sd card on Co-Pilot
• FEATURE REQ: file share capabilities (siab, html pages, exe files)
• ADD: disclaimer about saving it to local device or usb (what trace does Co-Pilot leave behind after a training?)

### Load Profile

• ADD: when you click, profile becomes highlighted OR boxes next to each for people to mark, then click load
• FUNCTION: description should reflect the description the trainer gives in the save frame

### Admin Configuration

• ADD: AP disclaimer somewhere, maybe this should be during the first part of the tutorial
o   Using the same AP for multiple trainings is connecting trainees unintentionally and may have severe consequences if someone is paying attention.

**Comment by megdeb** [comment]
@elationfoundation I am unsure how to link an image to each of these headings? Is there an easy way to do it that I am missing?

**Comment by seamustuohy** [comment]
### Responses
- FEEDBACK: any time there is a change to a password, access point name, rule, or profile - there must be a confirmation that the changes have been saved
  - "flashing" has been added to all pages to alert users of any changes or errors."
- NOTE: Welcome Tutorial has been removed.

#### New Profile
- FUNCTION: possibly pre-populate  some DNS blocking options since it is trickier
  - DNS blocking has an option pre-poulated on start.

#### Save Profile
- FEATURE REQ: file share capabilities (siab, html pages, exe files)
  - Rejected: Out of scope

#### Load Profile
- FUNCTION: description should reflect the description the trainer gives in the save frame
  - Descriptions have been removed (in the UI)

#### Admin Configuration
- ADD: AP disclaimer somewhere, maybe this should be during the first part of the tutorial
  - Using the same AP for multiple trainings is connecting trainees unintentionally and may have severe consequences if someone is paying attention.

### Issues Created
- disclaimers should be added (specifically regarding any traces of Co-Pilot that may be left behind for both the trainer and trainee)
  - Access Point 
-   Mention this can be reset at a later time
  - Access Point Password
-   Mention this can be reset at a later time
- Need to add a explanation for what each (action, target, sub-target) means
- ADD: text bubble or hyperlinks explaining URL, HTTP, HTTPS, DNS

#### New Profile
- ADD: labels
- FUNCTION: Be able to try rules out (with the ‘on’ button) before saving
- FUNCTION: possibly pre-populate  some DNS blocking options since it is trickier

#### Save Profile
- FUNCTION: be able to save profile to sd card on Co-Pilot
- ADD: disclaimer about saving it to local device or usb (what trace does Co-Pilot leave behind after a training?)

#### Admin Configuration
- ADD: AP disclaimer somewhere, maybe this should be during the first part of the tutorial
  - Using the same AP for multiple trainings is connecting trainees unintentionally and may have severe consequences if someone is paying attention.
